import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'

// Providers
import StyledComponentsRegistry from '@/lib/registry'
import ClientAppTheme from '@/styles/ClientAppTheme'

import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <ClientAppTheme injectGlobal reset>
            {children}
          </ClientAppTheme>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
